kind: Deployment
apiVersion: apps/v1beta1
metadata:
  labels:
    app: consumer
  name: consumer
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: consumer
      name: consumer
    spec:
      containers:
        - name: consumer
          image: gcr.io/hightowerlabs/consumer:0.0.1
          imagePullPolicy: Always
          env:
            - name: HOST_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
          args:
            - "-proxy=http://$(HOST_IP):80"
