apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    service: postgres
  name: postgres
  namespace: envoy-tutorial
spec:
  type: ClusterIP
  ports:
  - name: postgres
    port: 5432
  selector:
    service: postgres

