version: '3'

services:
  envoy:
    image: envoyproxy/envoy:v1.7.0
    volumes:
      - $PWD/envoy-config.yaml:/envoy-config.yaml
    command: ["envoy", "-c", "./envoy-config.yaml", "--v2-config-only", "-l", "debug"]
    # depends_on:
    #   - xds-server
    networks:
      - envoy-pilot_xds-demo
    ports:
      - "9901:9901"
      - "10000:10000"

networks:
  envoy-pilot_xds-demo:
    external: true