version: '3'

services:
  xds-server:
    build:
      context: .
      dockerfile: Dockerfile-xds-server
    security_opt:
      - seccomp:unconfined
    volumes:
      - $PWD/env_values.txt:/.env
    expose:
      - 7777
      - 2345
    ports: 
      - "2345:2345"
      - "9090:9090"
      - "7777:7777"
    networks:
      - envoy-pilot_xds-demo

networks:
  envoy-pilot_xds-demo:
    external: true