version: '3'

services:
## XDS Server
  xds-server:
    build:
      context: .
      dockerfile: Dockerfile-xds-server
    # command: "sh -c 'while true; do sleep 1000; done'"
    # command: "sh -c 'dlv --api-version 2 debug Envoy-Pilot/cmd/server/ -l 0.0.0.0:2345 --headless=true --log=true -- server'"
    # command: "sh -c 'go run /go/src/Envoy-Pilot/cmd/server/main.go'"
    security_opt:
      - seccomp:unconfined
    volumes:
      - $PWD/cmd/server/.env:/.env
    expose:
      - 7777
      - 2345
    ports: 
      - "2345:2345"
      - "9090:9090"
      - "7777:7777"
      - "8081:8081"
    networks:
      - envoy-pilot_xds-demo
    # depends_on:
    #   - consul-server-bootstrap

    # command: "sh -c 'while true; do sleep 1000; done'"
    # command: "sh -c 'dlv --api-version 2 debug Envoy-Pilot/cmd/server/ -l 0.0.0.0:2345 --headless=true --log=true -- server'"
    # command: "sh -c 'go run /go/src/Envoy-Pilot/cmd/server/main.go'"
    #command: ["./config/wait-for-it.sh", "consul-server-bootstrap:8500/v1/status/leader", "--", "echo", "'its up'"]
    #command: "sh -c 'apk add --no-cache curl; chmod +x config/wait-for-command.sh; sh config/wait-for-command.sh -t 30 -c \"curl -f http://localhost:8500/v1/status/leader\" && ./Envoy-Pilot'"

# Envoy
  envoy:
    image: envoyproxy/envoy:v1.7.0
    volumes:
      - $PWD/envoy-config.yaml:/envoy-config.yaml
    command: ["envoy", "-c", "./envoy-config.yaml", "--v2-config-only", "-l", "debug"]
    # depends_on:
    #   - xds-server
    networks:
      - envoy-pilot_xds-demo
    ports:
      - "9901:9901"
      - "10000:10000"

networks:
  envoy-pilot_xds-demo:
    external: true