apiVersion: v1
kind: Service
metadata:
  labels:
    run: rotor
  name: rotor
  namespace: default
spec:
  ports:
  - port: 50000
    protocol: TCP
    targetPort: 50000
  selector:
    run: rotor
  type: ClusterIP
