apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    service: edge-envoy
  name: edge-envoy
  namespace: envoy-tutorial
spec:
  type: NodePort
  ports:
  - name: edge-envoy
    nodePort: 30800
    port: 80
  selector:
    service: edge-envoy
