[[constraint]]
  name = "google.golang.org/grpc"
  revision = "f92cdcd7dcdc69e81b2d7b338479a19a8723cfa3"

[[constraint]]
  name = "k8s.io/client-go"
  revision = "7c69e980210777a6292351ac6873de083526f08e"

[[constraint]]
  name = "k8s.io/apimachinery"
  revision = "6134cb2da6d90597b0434e349f90f94fafc9ae51"

[[constraint]]
  name = "k8s.io/api"
  revision = "4d5cc6efc5e84aa19fb1bd3f911c16a6723c1bb7"

[[override]]
  name = "github.com/ugorji/go"
  revision = "708a42d246822952f38190a8d8c4e6b16a0e600c"

[[override]]
  name = "github.com/openzipkin/zipkin-go-opentracing"
  revision = "75836a71be339e7faf1b6b775e0703a875f484de"
  source = "https://github.com/mandarjog/zipkin-go-opentracing.git"

[[override]]
  revision = "d4df91709b724174aaf8a957f3edac3573be354e"
  name = "github.com/apache/thrift"

[[constraint]]
  branch = "master"
  name = "github.com/envoyproxy/go-control-plane"

[[constraint]]
  branch = "master"
  name = "github.com/google/go-jsonnet"
