apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    service: usersvc
  name: usersvc
  namespace: envoy-tutorial
spec:
  type: ClusterIP
  ports:
  - name: usersvc
    port: 80
    targetPort: 5000
  selector:
    service: usersvc

