# Default values for Envoy-simple.
# This is a YAML-formatted file.
# Declare name/value pairs to be passed into your templates.

replicaCount: 1
restartPolicy: Never

image: turbinelabs/rotor:0.19.0
imagePullPolicy: Always
