apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    service: edge-envoy
  name: edge-envoy
  namespace: envoy-tutorial
spec:
  type: ClusterIP
  ports:
  - name: edge-envoy
    port: 8000
    targetPort: 80
  selector:
    service: edge-envoy
