kind: Service
apiVersion: v1
metadata:
  name: kubernetes-envoy-sds
  namespace: kube-system
spec:
  selector:
    app: kubernetes-envoy-sds
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
